// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/mouad-eh/wasseet/proxy"
	"github.com/mouad-eh/wasseet/request"
	"net/http"
	"sync"
)

// Ensure, that BackendClientMock does implement proxy.BackendClient.
// If this is not the case, regenerate this file with moq.
var _ proxy.BackendClient = &BackendClientMock{}

// BackendClientMock is a mock implementation of proxy.BackendClient.
//
//	func TestSomethingThatUsesBackendClient(t *testing.T) {
//
//		// make and configure a mocked proxy.BackendClient
//		mockedBackendClient := &BackendClientMock{
//			DoFunc: func(clientRequest request.ClientRequest) (*http.Response, error) {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedBackendClient in code that requires proxy.BackendClient
//		// and then make assertions.
//
//	}
type BackendClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(clientRequest request.ClientRequest) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// ClientRequest is the clientRequest argument value.
			ClientRequest request.ClientRequest
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *BackendClientMock) Do(clientRequest request.ClientRequest) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("BackendClientMock.DoFunc: method is nil but BackendClient.Do was just called")
	}
	callInfo := struct {
		ClientRequest request.ClientRequest
	}{
		ClientRequest: clientRequest,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(clientRequest)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedBackendClient.DoCalls())
func (mock *BackendClientMock) DoCalls() []struct {
	ClientRequest request.ClientRequest
} {
	var calls []struct {
		ClientRequest request.ClientRequest
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
