// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/mouad-eh/wasseet/loadbalancer"
	"net/url"
	"sync"
)

// Ensure, that LoadBalancerMock does implement loadbalancer.LoadBalancer.
// If this is not the case, regenerate this file with moq.
var _ loadbalancer.LoadBalancer = &LoadBalancerMock{}

// LoadBalancerMock is a mock implementation of loadbalancer.LoadBalancer.
//
//	func TestSomethingThatUsesLoadBalancer(t *testing.T) {
//
//		// make and configure a mocked loadbalancer.LoadBalancer
//		mockedLoadBalancer := &LoadBalancerMock{
//			NextFunc: func() *url.URL {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedLoadBalancer in code that requires loadbalancer.LoadBalancer
//		// and then make assertions.
//
//	}
type LoadBalancerMock struct {
	// NextFunc mocks the Next method.
	NextFunc func() *url.URL

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *LoadBalancerMock) Next() *url.URL {
	if mock.NextFunc == nil {
		panic("LoadBalancerMock.NextFunc: method is nil but LoadBalancer.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedLoadBalancer.NextCalls())
func (mock *LoadBalancerMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}
